FROM debian:latest

# Install python and pip lastest version
RUN apt-get update && apt-get install -y python3 python3-pip nano cron sudo
RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
RUN cron

USER root
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD requirements.txt /app
ADD main.py /app

# Install any needed packages specified in requirements.txt
RUN pip3 install -r requirements.txt

# Share the folder "output" that is on the host with the container
VOLUME [ "/output" ]

# Create a cronjob to run the script every 15 minutes
COPY crontab.txt /opt
RUN crontab /opt/crontab.txt

# Run the command to start cron when the container starts
CMD ["cron", "-f"]